version: "3"
services:
  zookeeper:
    container_name: zookeeper
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    container_name: kafka
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://101.132.119.92:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
  kafka-manager:
    image: sheepkiller/kafka-manager                ## 镜像：开源的web管理kafka集群的界面
    environment:
      ZK_HOSTS: 101.132.119.92                   ## 修改:宿主机IP
    ports:
      - "9001:9000"
  wiznote:
    container_name: wiznote
    image: 'wiznote/wizserver:latest'
    ports:
      - '80:80'
      - '9269:9269/udp'
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - /mydata/wiznote:/wiz/storage